### ISSUE TITLE
Backend test.

### ISSUE THREAD

**Issue by btimby** [btimby/fulltext#44]
Add a CLI command that will import each backend in turn, and check that it's required CLI tools and Python modules are installed.

Ideally, each backend would raise `ImportError` when missing a Python module, or `MissingCommandException` if `which()` fails to find a required CLI tool.

Add `--test` to `__main__.py` so one can verify what needs to be installed to get `fulltext` fully operational.

**Comment by giampaolo** [comment]
Fixed.
