### ISSUE TITLE
Add HTML fallback parsing.

### ISSUE THREAD

**Issue by btimby** [btimby/fulltext#64]
If HTML or XML parsing fails, use a similar method to JSON fallback.

https://github.com/btimby/fulltext/commit/5e318a802f8511b06199e8f40dd3a35b2b5099dd

Use regex (`re.sub('<.*?>', ' ', html)`) to simply strip out tags leaving mostly text. The `bs4`/`lxml` approach is superior, but regex may be able to produce results when the sophisticated method cannot.

**Also:** investigate this.
https://stackoverflow.com/a/3400303

**Comment by giampaolo** [comment]
I couldn't get any html doc parsing to fail. Did you see happening this in production?

**Comment by btimby** [comment]
You know, historically I did and I made some changes to how BS4 is called. I don't have any specific failure cases.
